export const userTypes={
    ADD_USER:  "ADD_USER",
    SELECT_USER: "SELECT_USER",
    SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
    SIGN_IN_REQUEST: "SIGN_IN_REQUEST",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
    CLEAR_ERROR: "CLEAR_ERROR",
}