export {default as Profile} from './profile'
export {default as Servicios} from './servicios'
export {default as Login} from './login/login'
export {default as SignUp} from './login/signUp'
export {default as Home} from './home'
export {default as Turnos} from './turnos'
export {default as Pagos} from './pagos'